// Code generated by counterfeiter. DO NOT EDIT.
package serviceutilfakes

import (
	"sync"

	"github.com/pivotal-cf/spring-cloud-services-cli-plugin/serviceutil"
)

type FakeServiceInstanceResolver struct {
	GetManagementParametersStub        func(string, string, bool) (serviceutil.ManagementParameters, error)
	getManagementParametersMutex       sync.RWMutex
	getManagementParametersArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 bool
	}
	getManagementParametersReturns struct {
		result1 serviceutil.ManagementParameters
		result2 error
	}
	getManagementParametersReturnsOnCall map[int]struct {
		result1 serviceutil.ManagementParameters
		result2 error
	}
	GetServiceInstanceUrlStub        func(string, string) (string, error)
	getServiceInstanceUrlMutex       sync.RWMutex
	getServiceInstanceUrlArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getServiceInstanceUrlReturns struct {
		result1 string
		result2 error
	}
	getServiceInstanceUrlReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceInstanceResolver) GetManagementParameters(arg1 string, arg2 string, arg3 bool) (serviceutil.ManagementParameters, error) {
	fake.getManagementParametersMutex.Lock()
	ret, specificReturn := fake.getManagementParametersReturnsOnCall[len(fake.getManagementParametersArgsForCall)]
	fake.getManagementParametersArgsForCall = append(fake.getManagementParametersArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 bool
	}{arg1, arg2, arg3})
	fake.recordInvocation("GetManagementParameters", []interface{}{arg1, arg2, arg3})
	fake.getManagementParametersMutex.Unlock()
	if fake.GetManagementParametersStub != nil {
		return fake.GetManagementParametersStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getManagementParametersReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceInstanceResolver) GetManagementParametersCallCount() int {
	fake.getManagementParametersMutex.RLock()
	defer fake.getManagementParametersMutex.RUnlock()
	return len(fake.getManagementParametersArgsForCall)
}

func (fake *FakeServiceInstanceResolver) GetManagementParametersCalls(stub func(string, string, bool) (serviceutil.ManagementParameters, error)) {
	fake.getManagementParametersMutex.Lock()
	defer fake.getManagementParametersMutex.Unlock()
	fake.GetManagementParametersStub = stub
}

func (fake *FakeServiceInstanceResolver) GetManagementParametersArgsForCall(i int) (string, string, bool) {
	fake.getManagementParametersMutex.RLock()
	defer fake.getManagementParametersMutex.RUnlock()
	argsForCall := fake.getManagementParametersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceInstanceResolver) GetManagementParametersReturns(result1 serviceutil.ManagementParameters, result2 error) {
	fake.getManagementParametersMutex.Lock()
	defer fake.getManagementParametersMutex.Unlock()
	fake.GetManagementParametersStub = nil
	fake.getManagementParametersReturns = struct {
		result1 serviceutil.ManagementParameters
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceInstanceResolver) GetManagementParametersReturnsOnCall(i int, result1 serviceutil.ManagementParameters, result2 error) {
	fake.getManagementParametersMutex.Lock()
	defer fake.getManagementParametersMutex.Unlock()
	fake.GetManagementParametersStub = nil
	if fake.getManagementParametersReturnsOnCall == nil {
		fake.getManagementParametersReturnsOnCall = make(map[int]struct {
			result1 serviceutil.ManagementParameters
			result2 error
		})
	}
	fake.getManagementParametersReturnsOnCall[i] = struct {
		result1 serviceutil.ManagementParameters
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrl(arg1 string, arg2 string) (string, error) {
	fake.getServiceInstanceUrlMutex.Lock()
	ret, specificReturn := fake.getServiceInstanceUrlReturnsOnCall[len(fake.getServiceInstanceUrlArgsForCall)]
	fake.getServiceInstanceUrlArgsForCall = append(fake.getServiceInstanceUrlArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("GetServiceInstanceUrl", []interface{}{arg1, arg2})
	fake.getServiceInstanceUrlMutex.Unlock()
	if fake.GetServiceInstanceUrlStub != nil {
		return fake.GetServiceInstanceUrlStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getServiceInstanceUrlReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrlCallCount() int {
	fake.getServiceInstanceUrlMutex.RLock()
	defer fake.getServiceInstanceUrlMutex.RUnlock()
	return len(fake.getServiceInstanceUrlArgsForCall)
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrlCalls(stub func(string, string) (string, error)) {
	fake.getServiceInstanceUrlMutex.Lock()
	defer fake.getServiceInstanceUrlMutex.Unlock()
	fake.GetServiceInstanceUrlStub = stub
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrlArgsForCall(i int) (string, string) {
	fake.getServiceInstanceUrlMutex.RLock()
	defer fake.getServiceInstanceUrlMutex.RUnlock()
	argsForCall := fake.getServiceInstanceUrlArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrlReturns(result1 string, result2 error) {
	fake.getServiceInstanceUrlMutex.Lock()
	defer fake.getServiceInstanceUrlMutex.Unlock()
	fake.GetServiceInstanceUrlStub = nil
	fake.getServiceInstanceUrlReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceInstanceResolver) GetServiceInstanceUrlReturnsOnCall(i int, result1 string, result2 error) {
	fake.getServiceInstanceUrlMutex.Lock()
	defer fake.getServiceInstanceUrlMutex.Unlock()
	fake.GetServiceInstanceUrlStub = nil
	if fake.getServiceInstanceUrlReturnsOnCall == nil {
		fake.getServiceInstanceUrlReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getServiceInstanceUrlReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceInstanceResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getManagementParametersMutex.RLock()
	defer fake.getManagementParametersMutex.RUnlock()
	fake.getServiceInstanceUrlMutex.RLock()
	defer fake.getServiceInstanceUrlMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceInstanceResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ serviceutil.ServiceInstanceResolver = new(FakeServiceInstanceResolver)
