platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((dockerhub-mirror-registry))/library/golang
    tag: 1.22.1

inputs:
- name: src

outputs:
- name: built-plugin

run:
  path: src/ci/tasks/build.sh

params:
  CF_CLI_PLUGIN_INPUT: src
  BUILT_PLUGIN_OUTPUT: built-plugin
  VERSION: ""
