platform: linux

image_resource:
  type: registry-image
  source:
    repository: ((dockerhub-mirror-registry))/library/golang
    tag: 1.22.1

inputs:
- name: cf-cli-plugin

outputs:
- name: built-plugin

run:
  path: cf-cli-plugin/ci/tasks/build.sh

params:
  CF_CLI_PLUGIN_INPUT: cf-cli-plugin
  BUILT_PLUGIN_OUTPUT: built-plugin
  VERSION: ""
