// Code generated by counterfeiter. DO NOT EDIT.
package operationfakes

import (
	"sync"

	"github.com/pivotal-cf/spring-cloud-services-cli-plugin/instance"
)

type FakeOperation struct {
	IsServiceBrokerEndpointStub        func() bool
	isServiceBrokerEndpointMutex       sync.RWMutex
	isServiceBrokerEndpointArgsForCall []struct {
	}
	isServiceBrokerEndpointReturns struct {
		result1 bool
	}
	isServiceBrokerEndpointReturnsOnCall map[int]struct {
		result1 bool
	}
	RunStub        func(string, string) (string, error)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 string
		arg2 string
	}
	runReturns struct {
		result1 string
		result2 error
	}
	runReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOperation) IsServiceBrokerEndpoint() bool {
	fake.isServiceBrokerEndpointMutex.Lock()
	ret, specificReturn := fake.isServiceBrokerEndpointReturnsOnCall[len(fake.isServiceBrokerEndpointArgsForCall)]
	fake.isServiceBrokerEndpointArgsForCall = append(fake.isServiceBrokerEndpointArgsForCall, struct {
	}{})
	fake.recordInvocation("IsServiceBrokerEndpoint", []interface{}{})
	fake.isServiceBrokerEndpointMutex.Unlock()
	if fake.IsServiceBrokerEndpointStub != nil {
		return fake.IsServiceBrokerEndpointStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.isServiceBrokerEndpointReturns
	return fakeReturns.result1
}

func (fake *FakeOperation) IsServiceBrokerEndpointCallCount() int {
	fake.isServiceBrokerEndpointMutex.RLock()
	defer fake.isServiceBrokerEndpointMutex.RUnlock()
	return len(fake.isServiceBrokerEndpointArgsForCall)
}

func (fake *FakeOperation) IsServiceBrokerEndpointCalls(stub func() bool) {
	fake.isServiceBrokerEndpointMutex.Lock()
	defer fake.isServiceBrokerEndpointMutex.Unlock()
	fake.IsServiceBrokerEndpointStub = stub
}

func (fake *FakeOperation) IsServiceBrokerEndpointReturns(result1 bool) {
	fake.isServiceBrokerEndpointMutex.Lock()
	defer fake.isServiceBrokerEndpointMutex.Unlock()
	fake.IsServiceBrokerEndpointStub = nil
	fake.isServiceBrokerEndpointReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeOperation) IsServiceBrokerEndpointReturnsOnCall(i int, result1 bool) {
	fake.isServiceBrokerEndpointMutex.Lock()
	defer fake.isServiceBrokerEndpointMutex.Unlock()
	fake.IsServiceBrokerEndpointStub = nil
	if fake.isServiceBrokerEndpointReturnsOnCall == nil {
		fake.isServiceBrokerEndpointReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isServiceBrokerEndpointReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeOperation) Run(arg1 string, arg2 string) (string, error) {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("Run", []interface{}{arg1, arg2})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.runReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOperation) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeOperation) RunCalls(stub func(string, string) (string, error)) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeOperation) RunArgsForCall(i int) (string, string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOperation) RunReturns(result1 string, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeOperation) RunReturnsOnCall(i int, result1 string, result2 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeOperation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isServiceBrokerEndpointMutex.RLock()
	defer fake.isServiceBrokerEndpointMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOperation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ instance.Operation = new(FakeOperation)
