// Code generated by counterfeiter. DO NOT EDIT.
package httpclientfakes

import (
	"io"
	"sync"

	"github.com/pivotal-cf/spring-cloud-services-cli-plugin/httpclient"
)

type FakeAuthenticatedClient struct {
	DoAuthenticatedDeleteStub        func(string, string) (int, error)
	doAuthenticatedDeleteMutex       sync.RWMutex
	doAuthenticatedDeleteArgsForCall []struct {
		arg1 string
		arg2 string
	}
	doAuthenticatedDeleteReturns struct {
		result1 int
		result2 error
	}
	doAuthenticatedDeleteReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	DoAuthenticatedGetStub        func(string, string) (io.ReadCloser, int, error)
	doAuthenticatedGetMutex       sync.RWMutex
	doAuthenticatedGetArgsForCall []struct {
		arg1 string
		arg2 string
	}
	doAuthenticatedGetReturns struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}
	doAuthenticatedGetReturnsOnCall map[int]struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}
	DoAuthenticatedPostStub        func(string, string, string, string) (io.ReadCloser, int, error)
	doAuthenticatedPostMutex       sync.RWMutex
	doAuthenticatedPostArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}
	doAuthenticatedPostReturns struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}
	doAuthenticatedPostReturnsOnCall map[int]struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}
	DoAuthenticatedPutStub        func(string, string, string, string) (int, error)
	doAuthenticatedPutMutex       sync.RWMutex
	doAuthenticatedPutArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}
	doAuthenticatedPutReturns struct {
		result1 int
		result2 error
	}
	doAuthenticatedPutReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDelete(arg1 string, arg2 string) (int, error) {
	fake.doAuthenticatedDeleteMutex.Lock()
	ret, specificReturn := fake.doAuthenticatedDeleteReturnsOnCall[len(fake.doAuthenticatedDeleteArgsForCall)]
	fake.doAuthenticatedDeleteArgsForCall = append(fake.doAuthenticatedDeleteArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("DoAuthenticatedDelete", []interface{}{arg1, arg2})
	fake.doAuthenticatedDeleteMutex.Unlock()
	if fake.DoAuthenticatedDeleteStub != nil {
		return fake.DoAuthenticatedDeleteStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.doAuthenticatedDeleteReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDeleteCallCount() int {
	fake.doAuthenticatedDeleteMutex.RLock()
	defer fake.doAuthenticatedDeleteMutex.RUnlock()
	return len(fake.doAuthenticatedDeleteArgsForCall)
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDeleteCalls(stub func(string, string) (int, error)) {
	fake.doAuthenticatedDeleteMutex.Lock()
	defer fake.doAuthenticatedDeleteMutex.Unlock()
	fake.DoAuthenticatedDeleteStub = stub
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDeleteArgsForCall(i int) (string, string) {
	fake.doAuthenticatedDeleteMutex.RLock()
	defer fake.doAuthenticatedDeleteMutex.RUnlock()
	argsForCall := fake.doAuthenticatedDeleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDeleteReturns(result1 int, result2 error) {
	fake.doAuthenticatedDeleteMutex.Lock()
	defer fake.doAuthenticatedDeleteMutex.Unlock()
	fake.DoAuthenticatedDeleteStub = nil
	fake.doAuthenticatedDeleteReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedDeleteReturnsOnCall(i int, result1 int, result2 error) {
	fake.doAuthenticatedDeleteMutex.Lock()
	defer fake.doAuthenticatedDeleteMutex.Unlock()
	fake.DoAuthenticatedDeleteStub = nil
	if fake.doAuthenticatedDeleteReturnsOnCall == nil {
		fake.doAuthenticatedDeleteReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.doAuthenticatedDeleteReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGet(arg1 string, arg2 string) (io.ReadCloser, int, error) {
	fake.doAuthenticatedGetMutex.Lock()
	ret, specificReturn := fake.doAuthenticatedGetReturnsOnCall[len(fake.doAuthenticatedGetArgsForCall)]
	fake.doAuthenticatedGetArgsForCall = append(fake.doAuthenticatedGetArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("DoAuthenticatedGet", []interface{}{arg1, arg2})
	fake.doAuthenticatedGetMutex.Unlock()
	if fake.DoAuthenticatedGetStub != nil {
		return fake.DoAuthenticatedGetStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.doAuthenticatedGetReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGetCallCount() int {
	fake.doAuthenticatedGetMutex.RLock()
	defer fake.doAuthenticatedGetMutex.RUnlock()
	return len(fake.doAuthenticatedGetArgsForCall)
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGetCalls(stub func(string, string) (io.ReadCloser, int, error)) {
	fake.doAuthenticatedGetMutex.Lock()
	defer fake.doAuthenticatedGetMutex.Unlock()
	fake.DoAuthenticatedGetStub = stub
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGetArgsForCall(i int) (string, string) {
	fake.doAuthenticatedGetMutex.RLock()
	defer fake.doAuthenticatedGetMutex.RUnlock()
	argsForCall := fake.doAuthenticatedGetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGetReturns(result1 io.ReadCloser, result2 int, result3 error) {
	fake.doAuthenticatedGetMutex.Lock()
	defer fake.doAuthenticatedGetMutex.Unlock()
	fake.DoAuthenticatedGetStub = nil
	fake.doAuthenticatedGetReturns = struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedGetReturnsOnCall(i int, result1 io.ReadCloser, result2 int, result3 error) {
	fake.doAuthenticatedGetMutex.Lock()
	defer fake.doAuthenticatedGetMutex.Unlock()
	fake.DoAuthenticatedGetStub = nil
	if fake.doAuthenticatedGetReturnsOnCall == nil {
		fake.doAuthenticatedGetReturnsOnCall = make(map[int]struct {
			result1 io.ReadCloser
			result2 int
			result3 error
		})
	}
	fake.doAuthenticatedGetReturnsOnCall[i] = struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPost(arg1 string, arg2 string, arg3 string, arg4 string) (io.ReadCloser, int, error) {
	fake.doAuthenticatedPostMutex.Lock()
	ret, specificReturn := fake.doAuthenticatedPostReturnsOnCall[len(fake.doAuthenticatedPostArgsForCall)]
	fake.doAuthenticatedPostArgsForCall = append(fake.doAuthenticatedPostArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("DoAuthenticatedPost", []interface{}{arg1, arg2, arg3, arg4})
	fake.doAuthenticatedPostMutex.Unlock()
	if fake.DoAuthenticatedPostStub != nil {
		return fake.DoAuthenticatedPostStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.doAuthenticatedPostReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPostCallCount() int {
	fake.doAuthenticatedPostMutex.RLock()
	defer fake.doAuthenticatedPostMutex.RUnlock()
	return len(fake.doAuthenticatedPostArgsForCall)
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPostCalls(stub func(string, string, string, string) (io.ReadCloser, int, error)) {
	fake.doAuthenticatedPostMutex.Lock()
	defer fake.doAuthenticatedPostMutex.Unlock()
	fake.DoAuthenticatedPostStub = stub
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPostArgsForCall(i int) (string, string, string, string) {
	fake.doAuthenticatedPostMutex.RLock()
	defer fake.doAuthenticatedPostMutex.RUnlock()
	argsForCall := fake.doAuthenticatedPostArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPostReturns(result1 io.ReadCloser, result2 int, result3 error) {
	fake.doAuthenticatedPostMutex.Lock()
	defer fake.doAuthenticatedPostMutex.Unlock()
	fake.DoAuthenticatedPostStub = nil
	fake.doAuthenticatedPostReturns = struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPostReturnsOnCall(i int, result1 io.ReadCloser, result2 int, result3 error) {
	fake.doAuthenticatedPostMutex.Lock()
	defer fake.doAuthenticatedPostMutex.Unlock()
	fake.DoAuthenticatedPostStub = nil
	if fake.doAuthenticatedPostReturnsOnCall == nil {
		fake.doAuthenticatedPostReturnsOnCall = make(map[int]struct {
			result1 io.ReadCloser
			result2 int
			result3 error
		})
	}
	fake.doAuthenticatedPostReturnsOnCall[i] = struct {
		result1 io.ReadCloser
		result2 int
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPut(arg1 string, arg2 string, arg3 string, arg4 string) (int, error) {
	fake.doAuthenticatedPutMutex.Lock()
	ret, specificReturn := fake.doAuthenticatedPutReturnsOnCall[len(fake.doAuthenticatedPutArgsForCall)]
	fake.doAuthenticatedPutArgsForCall = append(fake.doAuthenticatedPutArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("DoAuthenticatedPut", []interface{}{arg1, arg2, arg3, arg4})
	fake.doAuthenticatedPutMutex.Unlock()
	if fake.DoAuthenticatedPutStub != nil {
		return fake.DoAuthenticatedPutStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.doAuthenticatedPutReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPutCallCount() int {
	fake.doAuthenticatedPutMutex.RLock()
	defer fake.doAuthenticatedPutMutex.RUnlock()
	return len(fake.doAuthenticatedPutArgsForCall)
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPutCalls(stub func(string, string, string, string) (int, error)) {
	fake.doAuthenticatedPutMutex.Lock()
	defer fake.doAuthenticatedPutMutex.Unlock()
	fake.DoAuthenticatedPutStub = stub
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPutArgsForCall(i int) (string, string, string, string) {
	fake.doAuthenticatedPutMutex.RLock()
	defer fake.doAuthenticatedPutMutex.RUnlock()
	argsForCall := fake.doAuthenticatedPutArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPutReturns(result1 int, result2 error) {
	fake.doAuthenticatedPutMutex.Lock()
	defer fake.doAuthenticatedPutMutex.Unlock()
	fake.DoAuthenticatedPutStub = nil
	fake.doAuthenticatedPutReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticatedClient) DoAuthenticatedPutReturnsOnCall(i int, result1 int, result2 error) {
	fake.doAuthenticatedPutMutex.Lock()
	defer fake.doAuthenticatedPutMutex.Unlock()
	fake.DoAuthenticatedPutStub = nil
	if fake.doAuthenticatedPutReturnsOnCall == nil {
		fake.doAuthenticatedPutReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.doAuthenticatedPutReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthenticatedClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.doAuthenticatedDeleteMutex.RLock()
	defer fake.doAuthenticatedDeleteMutex.RUnlock()
	fake.doAuthenticatedGetMutex.RLock()
	defer fake.doAuthenticatedGetMutex.RUnlock()
	fake.doAuthenticatedPostMutex.RLock()
	defer fake.doAuthenticatedPostMutex.RUnlock()
	fake.doAuthenticatedPutMutex.RLock()
	defer fake.doAuthenticatedPutMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthenticatedClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ httpclient.AuthenticatedClient = new(FakeAuthenticatedClient)
