---
slack-success-notification: &slack-success-notification
  put: alert
  params:
    icon_emoji: ":concourse:"
    username: concourse
    channel: ((scs-slack-notification-channel))
    text: "<!here> CF CLI plugin $BUILD_JOB_NAME has succeeded with build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME>!"

slack-failure-notification: &slack-failure-notification
  put: alert
  params:
    icon_emoji: ":animal:"
    username: concourse
    channel: ((scs-slack-failure-channel))
    text: "<!here> CF CLI plugin $BUILD_JOB_NAME has failed with build <https://scs.ci.springapps.io/builds/$BUILD_ID|$BUILD_NAME>!"

jobs:
- name: build-plugin
  serial: true
  plan:
  - in_parallel:
    - get: cf-cli-plugin
      trigger: true
    - get: version
      params:
        bump: patch
  - task: build-plugin
    file: cf-cli-plugin/ci/tasks/build.yml
    on_success:
      in_parallel:
      - put: cf-cli-plugin-storage
        params:
          file: built-plugin/spring-cloud-services-cli-plugin-darwin-amd64-*
      - put: cf-cli-plugin-storage
        params:
          file: built-plugin/spring-cloud-services-cli-plugin-linux-386-*
      - put: cf-cli-plugin-storage
        params:
          file: built-plugin/spring-cloud-services-cli-plugin-linux-amd64-*
      - put: cf-cli-plugin-storage
        params:
          file: built-plugin/spring-cloud-services-cli-plugin-windows-386-*
      - put: cf-cli-plugin-storage
        params:
          file: built-plugin/spring-cloud-services-cli-plugin-windows-amd64-*
      - put: version
        params: {file: version/version}
  on_success: *slack-success-notification
  on_failure: *slack-failure-notification

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-cli-plugin
  type: git
  source:
    uri: ((github-url-cf-cli-plugin))
    branch: master
    ignore_paths: [version]

- name: version
  type: semver
  source:
    driver: git
    uri: ((github-url-cf-cli-plugin))
    branch: master
    file: version
    initial_version: 0.0.0

- name: cf-cli-plugin-storage
  type: s3
  source:
    bucket: ((scs-cf-cli-s3-bucket-name))
    regexp: spring-cloud-services-cli-plugin-(.*)
    access_key_id: ((scs-s3-access-key-id))
    secret_access_key: ((scs-s3-secret-access-key))

- name: alert
  type: slack-notification
  source:
    # Default channel is #scs-firehose
    url: ((scs-slack-webhook))
