---
success-notification: &success-notification
  put: notify
  inputs: detect
  no_get: true
  params:
    alert_type: success
    message: SCS CF CLI Plugin

failure-notification: &failure-notification
  put: notify
  inputs: detect
  no_get: true
  params:
    alert_type: failed
    message: SCS CF CLI Plugin

jobs:
  - name: build
    serial: true
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - get: golang-image
      - task: build
        image: golang-image
        file: src/ci/tasks/build.yml
        params:
          VERSION: 0.0.0-build.1
    on_success: *success-notification
    on_failure: *failure-notification

  - name: release
    plan:
      - in_parallel:
          - do:
              - get: version
                trigger: true
              - load_var: release-version
                file: version/.git/ref
                reveal: true
          - get: src
            passed: [build]
          - get: golang-image
      - task: build
        image: golang-image
        file: src/ci/tasks/build.yml
        params:
          VERSION: ((.:release-version))
      - put: release
        inputs: detect
        params:
          name: version/.git/ref
          tag: version/.git/ref
          globs:
            - built-plugin/spring-cloud-services-cli-plugin-*
    on_success: *success-notification
    on_failure: *failure-notification

resource_types:
  - name: notify-type
    type: registry-image
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/epic2/concourse-google-chat-alert-resource
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: dev

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://((github.token))@github.com/pivotal-cf/spring-cloud-services-cli-plugin.git
      branch: ((branch))

  - name: version
    type: git
    icon: tag
    source:
      uri: https://((github.token))@github.com/pivotal-cf/spring-cloud-services-cli-plugin.git
      branch: ((branch))
      tag_filter: v[1-9].*
      fetch_tags: true

  - name: release
    type: github-release
    icon: github
    source:
      owner: pivotal-cf
      repository: spring-cloud-services-cli-plugin
      access_token: ((github.token))
      pre_release: true
      release: false
      tag_filter: ^v(d+\.d+\.\d+(?:-(?:alpha|beta|rc)\.\d+)?)$

  - name: notify
    type: notify-type
    icon: bullhorn
    source:
      url: ((gspace.webhook))

  - name: golang-image
    type: registry-image
    icon: docker
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/library/golang
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 1.26.0
