---
slack-success-notification: &slack-success-notification
  put: alert
  params:
    icon_emoji: ":concourse:"
    username: concourse
    channel: ((scs-slack-notification-channel))
    text: "<!here> CF CLI plugin $BUILD_JOB_NAME has succeeded with build <$ATC_EXTERNAL_URL/builds/$BUILD_ID|$BUILD_NAME>!"

slack-failure-notification: &slack-failure-notification
  put: alert
  params:
    icon_emoji: ":animal-1252:"
    username: concourse
    channel: ((scs-slack-failure-channel))
    text: "<!here> CF CLI plugin $BUILD_JOB_NAME has failed with build <$ATC_EXTERNAL_URL/builds/$BUILD_ID|$BUILD_NAME>!"

jobs:
- name: build-plugin
  serial: true
  plan:
  - in_parallel:
    - get: cf-cli-plugin
      trigger: true
    - get: build-version
  - load_var: build-version
    file: build-version/version
    reveal: true
  - put: build-version
    inputs: detect
    params:
      pre: build
    no_get: true
  - task: build-plugin
    file: cf-cli-plugin/ci/tasks/build.yml
    params:
      VERSION: ((.:build-version))
  on_success: *slack-success-notification
  on_failure: *slack-failure-notification

- name: release-plugin
  plan:
  - in_parallel:
    - do:
      - get: release-tag
        trigger: true
      - load_var: release-version
        file: release-tag/.git/ref
        reveal: true
    - get: cf-cli-plugin
      passed: [ build-plugin ]
    - get: build-version
      passed: [ build-plugin ]
  - task: build-plugin
    file: cf-cli-plugin/ci/tasks/build.yml
    params:
      VERSION: ((.:release-version))
  - put: github-release
    inputs: detect
    params:
      name: release-tag/.git/ref
      tag: release-tag/.git/ref
      globs:
      - built-plugin/spring-cloud-services-cli-plugin-*
  on_success: *slack-success-notification
  on_failure: *slack-failure-notification

resource_types:
- name: slack-notification
  type: registry-image
  source:
    repository: ((dockerhub-mirror-registry))/cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-cli-plugin
  type: git
  icon: github
  source:
    uri: https://((github/scsbot.token))@((github-url-cf-cli-plugin))
    branch: ((branch))

- name: release-tag
  type: git
  icon: github
  source:
    uri: https://((github/scsbot.token))@((github-url-cf-cli-plugin))
    branch: ((branch))
    tag_filter: v[1-9].*
    fetch_tags: true

- name: github-release
  type: github-release
  icon: github
  source:
    owner: pivotal-cf
    repository: spring-cloud-services-cli-plugin
    access_token: ((github/scsbot.token))
    pre_release: true
    release: false
    tag_filter: ^v(d+\.d+\.\d+(?:-(?:alpha|beta|rc)\.\d+)?)$

- name: build-version
  type: semver
  icon: counter
  source:
    driver: s3
    bucket: ((scs-cf-cli-s3-bucket-name))
    key: current-version
    access_key_id: ((scs-s3-access-key-id))
    secret_access_key: ((scs-s3-secret-access-key))
    initial_version: 1.0.0-build.1

- name: alert
  type: slack-notification
  icon: slack
  source:
    # Default channel is #scs-firehose
    url: ((scs-slack-webhook))
